---
# Inventaire pour d√©ploiement local
# Utilisation: ansible-playbook -i inventory/hosts.local.yml playbooks/deploy.yml

all:
  hosts:
    localhost:
      ansible_connection: local
      frontend_url: http://localhost:3000
      api_base_url: http://localhost:3001
      app_name: phishguard
      app_user: "{{ ansible_user | default('root') }}"
      app_dir: "{{ ansible_env.HOME }}/phishguard"

