---
# Inventaire pour d√©ploiement local Ubuntu
# Utilisation: sudo ./install.sh local

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: "{{ ansible_user | default('root') }}"
      frontend_url: http://localhost:3000
      api_base_url: http://localhost:3001
      app_name: phishguard
      app_user: "{{ app_user | default('root') }}"
      app_dir: "/opt/phishguard"
