---
# Inventaire pour d√©ploiement local Ubuntu
# Utilisation: ./deploy.sh local

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: "{{ ansible_env.USER }}"
      frontend_url: http://localhost:3000
      api_base_url: http://localhost:3001
      app_name: phishguard
      app_user: "{{ ansible_env.USER }}"
      app_dir: "{{ ansible_env.HOME }}/phishguard"
